// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FCM
{
    internal sealed partial class Vsix
    {
        public const string Id = "FCM.3aef2fbe-84b7-41de-9f17-e4e1171d7baa";
        public const string Name = "Functional Code Map for visual studio 2022";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mohamad Makkawi";
        public const string Tags = "";
    }
}
