// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FCM
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommandVisisiblityString = "e392fc72-e6da-4a70-9473-41c6d6aea9a6";
        public static Guid CommandVisisiblity = new Guid(CommandVisisiblityString);

        public const string FCMString = "e392fc72-e6da-4a70-9473-41c6d6aea9a5";
        public static Guid FCM = new Guid(FCMString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}